version: '3.8'

services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - test-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=test
      - MONGO_INITDB_DATABASE=test_db

networks:
  test-network:
    driver: bridge